// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/main-menu/MainMenu.tsx": () => import("../components/mockups/main-menu/MainMenu.tsx"),
  "./components/mockups/messenger-carousel/CarouselPreview.tsx": () => import("../components/mockups/messenger-carousel/CarouselPreview.tsx")
};
