import { pgTable, serial, boolean, text, integer, timestamp } from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod/v4";

export const settingsTable = pgTable("settings", {
  id: serial("id").primaryKey(),
  botEnabled: boolean("bot_enabled").notNull().default(false),
  facebookBotEnabled: boolean("facebook_bot_enabled").notNull().default(false),
  instagramBotEnabled: boolean("instagram_bot_enabled").notNull().default(false),
  shadowLearningEnabled: boolean("shadow_learning_enabled").notNull().default(false),
  schedulerEnabled: boolean("scheduler_enabled").notNull().default(false),
  scheduleStart: text("schedule_start").notNull().default("12:00"),
  scheduleEnd: text("schedule_end").notNull().default("17:00"),
  ageFilterMin: integer("age_filter_min").notNull().default(1),
  ageFilterMax: integer("age_filter_max").notNull().default(4),
  customAgeFilter: text("custom_age_filter"),
  metaAppId: text("meta_app_id"),
  metaAppSecret: text("meta_app_secret"),
  facebookPageId: text("facebook_page_id"),
  instagramAccountId: text("instagram_account_id"),
  instagramWebhookActive: boolean("instagram_webhook_active").notNull().default(false),
  metaAccessToken: text("meta_access_token"),
  instagramAccessToken: text("instagram_access_token"),
  whatsappAdminNumber: text("whatsapp_admin_number"),
  webhookVerifyToken: text("webhook_verify_token"),
  tokenExpiresAt: integer("token_expires_at"),
  twilioAccountSid: text("twilio_account_sid"),
  twilioAuthToken: text("twilio_auth_token"),
  twilioFromNumber: text("twilio_from_number"),
  viberApiKey: text("viber_api_key"),
  telegramBotToken: text("telegram_bot_token"),
  telegramChatId: text("telegram_chat_id"),
  language: text("language").notNull().default("both"),
  deliveryFees: text("delivery_fees"),
  adminPassword: text("admin_password"),
  resetOtp: text("reset_otp"),
  resetOtpExpiry: integer("reset_otp_expiry"),
  recoveryEmail: text("recovery_email"),
  smtpUser: text("smtp_user"),
  smtpPass: text("smtp_pass"),
  recoveryKey: text("recovery_key"),
  storefrontSuggestions: text("storefront_suggestions"),
  carouselBanners: text("carousel_banners"),
  installBannerEnabled: boolean("install_banner_enabled").notNull().default(true),
  installBannerMessage: text("install_banner_message"),
  tickerMessages: text("ticker_messages"),
  tickerColors: text("ticker_colors"),
  notesColors: text("notes_colors"),
  btnAnimationType: text("btn_animation_type").notNull().default("neon-trace"),
  btnAnimations: text("btn_animations"),
  beeEnabled: boolean("bee_enabled").notNull().default(true),
  beeRedeemThreshold: integer("bee_redeem_threshold").notNull().default(1000),
  beeRedeemValueIqd: integer("bee_redeem_value_iqd").notNull().default(2000),
  beeNotes: text("bee_notes"),
  fortuneEnabled: boolean("fortune_enabled").notNull().default(false),
  aiModelText: text("ai_model_text").notNull().default("gpt-4o"),
  aiModelImage: text("ai_model_image").notNull().default("gpt-4o"),
  // ── Bot General Q&A Text ─────────────────────────────────────────────────
  generalQaText: text("general_qa_text"),
  // ── Bot Settings ────────────────────────────────────────────────────────
  disableSavedReplies: boolean("disable_saved_replies").notNull().default(false),
  welcomeFlowEnabled: boolean("welcome_flow_enabled").notNull().default(false),
  welcomeMessages: text("welcome_messages"),
  menuItems: text("menu_items"),
  menuLangPrompt: text("menu_lang_prompt"),
  menuArPrompt: text("menu_ar_prompt"),
  menuKuPrompt: text("menu_ku_prompt"),
  systemPromptOverride: text("system_prompt_override"),
  historyWindowSize: integer("history_window_size").notNull().default(50),
  maintenanceMode: boolean("maintenance_mode").notNull().default(false),
  botMode: text("bot_mode").notNull().default("both"),
  blacklistKeywords: text("blacklist_keywords"),
  slangMapper: text("slang_mapper"),
  beeResetScheduledAt: timestamp("bee_reset_scheduled_at"),
  fortuneResetScheduledAt: timestamp("fortune_reset_scheduled_at"),
  cartLayout: text("cart_layout"),
  cartColors: text("cart_colors"),
  storefrontGridLayout: text("storefront_grid_layout").notNull().default("2"),
  storefrontNotes: text("storefront_notes"),
  googleClientId: text("google_client_id"),
  jwtSecret: text("jwt_secret"),
  pwaArrowSettings: text("pwa_arrow_settings"),
  footerSettings: text("footer_settings"),
  // ── Interactive Menu (Facebook Persistent Menu) ──────────────────────────
  interactiveMenuEnabled: boolean("interactive_menu_enabled").notNull().default(false),
  interactiveMenuItems: text("interactive_menu_items"),
  // ── Tutorial Video ────────────────────────────────────────────────────────
  tutorialVideoEnabled: boolean("tutorial_video_enabled").notNull().default(false),
  tutorialVideoAttachmentId: text("tutorial_video_attachment_id"),
  tutorialVideoUrl: text("tutorial_video_url"),
  tutorialImages: text("tutorial_images"),
  tutorialImagesEnabled: boolean("tutorial_images_enabled").notNull().default(false),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const insertSettingsSchema = createInsertSchema(settingsTable).omit({ id: true, updatedAt: true });
export type InsertSettings = z.infer<typeof insertSettingsSchema>;
export type Settings = typeof settingsTable.$inferSelect;
